<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            // Akademik
            [
                'title' => 'Medali Emas Olimpiade Sains Nasional Fisika',
                'description' => 'Siswa SMAN 1 Denpasar berhasil meraih medali emas dalam Olimpiade Sains Nasional bidang Fisika tingkat nasional.',
                'category' => 'Akademik',
                'year' => 2025,
                'level' => 'national',
                'organizer' => 'Kementerian Pendidikan dan Kebudayaan',
                'participants' => ['I Putu Bagus Arya Dharma'],
                'coach' => 'Drs. I Wayan Sudana, M.Pd',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-09-15',
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'title' => 'Juara 1 Kompetisi Matematika dan Statistika Udayana',
                'description' => 'Tim SMAN 1 Denpasar meraih juara pertama dalam Kompetisi Matematika dan Statistika tingkat SMA se-Bali yang diselenggarakan oleh Universitas Udayana.',
                'category' => 'Akademik',
                'year' => 2025,
                'level' => 'regional',
                'organizer' => 'Universitas Udayana',
                'participants' => ['Ni Made Ayu Putri', 'I Kadek Surya Pratama'],
                'coach' => 'I Gede Artha, S.Pd, M.Si',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-08-20',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'title' => 'Medali Perak International Economics Olympiad',
                'description' => 'Siswa SMAN 1 Denpasar berhasil meraih medali perak di ajang International Economics Olympiad di Baku, Azerbaijan.',
                'category' => 'Akademik',
                'year' => 2025,
                'level' => 'international',
                'organizer' => 'International Economics Olympiad Committee',
                'participants' => ['I Putu Dickson Partha Hartopo'],
                'coach' => 'Dr. Ni Luh Gede Ari, M.Ec',
                'medal_type' => 'silver',
                'rank' => 2,
                'achievement_date' => '2025-07-25',
                'is_featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
            // Olahraga
            [
                'title' => 'Medali Emas Renang ASEAN School Games',
                'description' => 'Atlet renang SMAN 1 Denpasar meraih medali emas di nomor 100m gaya kupu-kupu pada ASEAN School Games di Brunei Darussalam.',
                'category' => 'Olahraga',
                'year' => 2025,
                'level' => 'international',
                'organizer' => 'ASEAN School Games Committee',
                'participants' => ['I Nyoman Gede Yajamana Swaha'],
                'coach' => 'I Made Sugiarta, S.Pd',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-06-10',
                'is_featured' => true,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'title' => 'Juara 2 DBL All-Star Indonesia',
                'description' => 'Tim basket putra SMAN 1 Denpasar lolos seleksi dan akan mewakili Indonesia di DBL All-Star 2025 di Amerika Serikat.',
                'category' => 'Olahraga',
                'year' => 2025,
                'level' => 'national',
                'organizer' => 'Development Basketball League',
                'participants' => ['I Gede Arya Wibawa', 'Kadek Surya Putra'],
                'coach' => 'I Ketut Sudiana, S.Pd',
                'medal_type' => 'silver',
                'rank' => 2,
                'achievement_date' => '2025-05-20',
                'is_featured' => true,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'title' => 'Medali Emas Taekwondo Kadisdikpora Cup',
                'description' => 'Atlet taekwondo SMAN 1 Denpasar meraih medali emas di Kadisdikpora Bali Cup 2025.',
                'category' => 'Olahraga',
                'year' => 2025,
                'level' => 'regional',
                'organizer' => 'Dinas Pendidikan Provinsi Bali',
                'participants' => ['Abhikara Putra Wijaya'],
                'coach' => 'Sabeum Ni Made Surya',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-04-15',
                'is_featured' => false,
                'is_active' => true,
                'order' => 6,
            ],
            // Seni
            [
                'title' => 'Juara 1 FLS2N Tari Kreasi Tingkat Provinsi',
                'description' => 'Tim tari SMAN 1 Denpasar meraih juara pertama Festival Lomba Seni Siswa Nasional kategori Tari Kreasi tingkat Provinsi Bali.',
                'category' => 'Seni',
                'year' => 2025,
                'level' => 'regional',
                'organizer' => 'Dinas Pendidikan Provinsi Bali',
                'participants' => ['Ni Putu Ayu Dewi', 'Ni Kadek Sri Lestari', 'Ni Made Rai Putri'],
                'coach' => 'Ni Wayan Pagawati, S.Sn',
                'medal_type' => 'winner',
                'rank' => 1,
                'achievement_date' => '2025-05-05',
                'is_featured' => true,
                'is_active' => true,
                'order' => 7,
            ],
            [
                'title' => 'Juara 3 Lomba Utsawa Dharma Gita Se-Bali',
                'description' => 'Tim pesantian SMAN 1 Denpasar berhasil meraih juara 3 putra dan putri di Lomba Utsawa Dharma Gita tingkat Provinsi Bali.',
                'category' => 'Seni',
                'year' => 2025,
                'level' => 'regional',
                'organizer' => 'PHDI Provinsi Bali',
                'participants' => ['Tim Pesantian Putra', 'Tim Pesantian Putri'],
                'coach' => 'I Kadek Sumada, S.Pd.H',
                'medal_type' => 'bronze',
                'rank' => 3,
                'achievement_date' => '2025-03-25',
                'is_featured' => false,
                'is_active' => true,
                'order' => 8,
            ],
            // Teknologi
            [
                'title' => 'Medali Emas International Young Entrepreneur Network',
                'description' => 'Tim KISS SMAN 1 Denpasar meraih medali emas di ajang inovasi internasional IYEN 2025 dengan inovasi Ilmajinasi.id untuk pendidikan inklusif.',
                'category' => 'Teknologi',
                'year' => 2025,
                'level' => 'international',
                'organizer' => 'International Young Entrepreneur Network',
                'participants' => ['I Made Surya Dharma', 'Ni Putu Eka Pratiwi'],
                'coach' => 'I Gede Harry Wirawan, S.Pd',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-04-10',
                'is_featured' => true,
                'is_active' => true,
                'order' => 9,
            ],
            [
                'title' => 'Juara 2 Walikota Cup E-Sports 2025',
                'description' => 'Tim Mobile Legends SMAN 1 Denpasar meraih juara 2 di turnamen E-Sports Walikota Cup Denpasar 2025.',
                'category' => 'Teknologi',
                'year' => 2025,
                'level' => 'regional',
                'organizer' => 'Pemerintah Kota Denpasar',
                'participants' => ['Tim MLBB SMAN 1 Denpasar'],
                'coach' => 'I Kadek Swartana Putra, S.Pd',
                'medal_type' => 'silver',
                'rank' => 2,
                'achievement_date' => '2025-02-20',
                'is_featured' => false,
                'is_active' => true,
                'order' => 10,
            ],
            // International
            [
                'title' => 'Silver Medal Japan Design Ideas Invention Expo',
                'description' => 'Tim inovasi SMAN 1 Denpasar meraih silver medal di International Japan Design Ideas Invention Expo dengan karya inovatif bidang lingkungan.',
                'category' => 'Teknologi',
                'year' => 2024,
                'level' => 'international',
                'organizer' => 'Japan Design Association',
                'participants' => ['I Putu Gede Arya', 'Ni Made Sri Dewi'],
                'coach' => 'Drs. I Wayan Wirawan, M.Pd',
                'medal_type' => 'silver',
                'rank' => 2,
                'achievement_date' => '2024-11-15',
                'is_featured' => true,
                'is_active' => true,
                'order' => 11,
            ],
            [
                'title' => 'Juara 1 Olimpiade Fisika Nasional PSC Undiksha',
                'description' => 'Tim fisika SMAN 1 Denpasar meraih piala bergilir dan juara 1 di Olimpiade Fisika Nasional Physics Summit Competition Undiksha 2025.',
                'category' => 'Akademik',
                'year' => 2025,
                'level' => 'national',
                'organizer' => 'Universitas Pendidikan Ganesha',
                'participants' => ['I Gede Artha Dharma', 'Ni Putu Ayu Lestari'],
                'coach' => 'Drs. I Nyoman Astawa, M.Pd',
                'medal_type' => 'gold',
                'rank' => 1,
                'achievement_date' => '2025-10-05',
                'is_featured' => true,
                'is_active' => true,
                'order' => 12,
            ],
        ];

        foreach ($achievements as $data) {
            Achievement::create($data);
        }
    }
}
